
from shared.errors import ResourceNotFoundException


class UserNotFoundException(ResourceNotFoundException):
    pass